### ISSUE TITLE
vcfallelicprimitives incorrect phasing

### ISSUE THREAD

**Issue by brendanofallon** [vcflib/vcflib#132]
Looks like vcfallelicprimitives can sometimes produce incorrectly phased output, and the behavior is weirdly inconsistent. For instance, the input variants:

```
8       129879402       .       GA      GAACCA  3150.85 .       .   GT:DP:RO:QR:AO:QA:GL    0/1:156:80:4560:75:4275:-325.579,0,-350.435
8       129879404       .       AA      AGA     3025.9  .       .   GT:DP:RO:QR:AO:QA:GL    0/1:161:83:4731:74:4218:-316.995,0,-361.736
```

become phased, like this:

```
8       129879402       .       G       GAACC   3150.85 .       AC=1;AF=0.5;LEN=4;TYPE=ins      GT      0|1
8       129879404       .       A       AG      3025.90 .       AC=1;AF=0.5;LEN=1;TYPE=ins      GT      0|1
```

Weirdly, the very similar input produced by the GATK-UG:

```
8       129879402       .       G       GAACC   5087.73 .       .    GT:AD:DP:GQ:PL  0/1:76,80:162:99:5125,0,4539
8       129879404       .       A       AG      2964.73 .       .    GT:AD:DP:GQ:PL  0/1:87,77:166:99:3002,0,3190
```

results in _unphased_ output:

```
8       129879402       .       G       GAACC   5087.73 .       .    GT:AD:DP:GQ:PL  0/1:76,80:162:99:5125,0,4539
8       129879404       .       A       AG      2964.73 .       .    GT:AD:DP:GQ:PL  0/1:87,77:166:99:3002,0,3190
```

 The first scenario appears incorrect, and can cause phase-aware comparison tools (vcfeval, hap.py, vgraph, etc) to produce mismatches on data that did match prior to running the tool. I believe this is related to issue #98

**Comment by ekg** [comment]
If you normalize first with vt normalize is the first issue still present?

**Comment by brendanofallon** [comment]
No, running the variants first though vt normalize, then through vcfallelicprimitives results in correct, unphased output.

**Comment by ekg** [comment]
That's reassuring but it shouldn't produce incorrect output in the first
place. I'll see what I can do.

**Comment by Lenbok** [comment]
I think the issue here is that the phased calls are being inserted into the implicit phase set, which is globally shared for all variants on the same chromosome. From the VCF spec:

> All phased genotypes that do not contain a PS subfield are 
> assumed to belong to the same phased set.

And since in this case these originated from separate variants there is the potential for them to be inconsistent. I imagine that vcfallelicprimitives only knows about the consistency of phasing for a single variant which is split into multiple, so the correct solution would be to add an appropriate `PS` annotation for each distinct phase set that vcfallelicprimitives has introduced (like `vt decompose_blocksub -p` produces)

I vaguely recall that very early versions of the VCF spec had some notion of phased genotypes being with respect to the preceding phased call. I can't find any of those directly (`PS` was introduced in 4.1), but I think several tools have not been updated to comply with the actual spec, e.g. http://gatkforums.broadinstitute.org/gatk/discussion/45/purpose-and-operation-of-read-backed-phasing says:

> The local haplotype and its phasing is encoded in the VCF file as a "|" symbol (which indicates that the alleles of the genotype correspond to the same order as the alleles for the genotype at the preceding variant site).

Which is not going to be correct unless the resulting read backed phasing is consistent across a whole chromosome! At this stage I think the implicit phase set should only realistically be used for pedigree-based phasing.
