### ISSUE TITLE
Test failures on s390x prevent build from completing on Debian/Ubuntu

### ISSUE THREAD

**Issue by sergiodj** [vcflib/vcflib#386]
Hi,

libvcflib currently fails to build from source on s390x on Debian/Ubuntu because of testsuite failures:

```
make[1]: Entering directory '/<<PKGBUILDDIR>>'
cp obj-s390x-linux-gnu/CTestTestfile.cmake test/
ln -sf obj-s390x-linux-gnu/ build
cd test && ctest .
Test project /<<PKGBUILDDIR>>/test
    Start 1: realign
1/9 Test #1: realign ..........................***Failed    0.05 sec
    Start 2: pyvcflib
2/9 Test #2: pyvcflib .........................   Passed    0.05 sec
    Start 3: vcflib-api
3/9 Test #3: vcflib-api .......................   Passed    0.05 sec
    Start 4: vcf2tsv
4/9 Test #4: vcf2tsv ..........................   Passed    0.08 sec
    Start 5: vcfallelicprimitives
5/9 Test #5: vcfallelicprimitives .............***Failed    0.53 sec
    Start 6: vcfwave
6/9 Test #6: vcfwave ..........................***Failed    0.47 sec
    Start 7: vcffilter
7/9 Test #7: vcffilter ........................   Passed    0.14 sec
    Start 8: vcfnulldotslashdot
8/9 Test #8: vcfnulldotslashdot ...............   Passed    0.06 sec
    Start 9: doc/vcfintersect
9/9 Test #9: doc/vcfintersect .................   Passed    0.05 sec

67% tests passed, 3 tests failed out of 9

Total Test time (real) =   1.54 sec

The following tests FAILED:
	  1 - realign (Failed)
	  5 - vcfallelicprimitives (Failed)
	  6 - vcfwave (Failed)
Errors while running CTest
```

I understand that having access to a s390x machine is not always feasible, so I can try to provide more details if needed.

Thanks.

**Comment by vpa1977** [comment]
The realign test fail due to libwfa2 library issue

Running integration tests for libwfa2 via `./tests/wfa.utest.sh` produces the following results on amd64 platform:

-----------------------
> Comparing ./tests vs ./tests/wfa.utest.check
[UTest::test.affine2p] OK
[UTest::test.affine] OK
[UTest::test.affine.p0] OK
[UTest::test.affine.p1] OK
[UTest::test.affine.p2] OK
[UTest::test.affine.p3] OK
[UTest::test.affine.p4] OK
[UTest::test.affine.p5] OK
[UTest::test.affine.wfapt0] OK
[UTest::test.affine.wfapt1] OK
[UTest::test.biwfa.affine2p] OK
[UTest::test.biwfa.affine] OK
[UTest::test.biwfa.affine.p0] OK
[UTest::test.biwfa.affine.p1] OK
[UTest::test.biwfa.affine.p2] OK
[UTest::test.biwfa.affine.p3] OK
[UTest::test.biwfa.affine.p4] OK
[UTest::test.biwfa.affine.p5] OK
[UTest::test.biwfa.affine.wfapt0] OK
[UTest::test.biwfa.affine.wfapt1] OK
[UTest::test.biwfa.edit] OK
[UTest::test.biwfa.indel] OK
[UTest::test.biwfa.score.affine2p] OK
[UTest::test.biwfa.score.affine] OK
[UTest::test.biwfa.score.affine.p0] OK
[UTest::test.biwfa.score.affine.p1] OK
[UTest::test.biwfa.score.affine.p2] OK
[UTest::test.biwfa.score.affine.p3] OK
[UTest::test.biwfa.score.affine.p4] OK
[UTest::test.biwfa.score.affine.p5] OK
[UTest::test.biwfa.score.affine.wfapt0] OK
[UTest::test.biwfa.score.affine.wfapt1] OK
[UTest::test.biwfa.score.edit] OK
[UTest::test.biwfa.score.indel] OK
[UTest::test.edit] OK
[UTest::test.indel] OK
[UTest::test.pb.affine2p] OK
[UTest::test.pb.affine] OK
[UTest::test.pb.affine.p0] OK
[UTest::test.pb.affine.p1] OK
[UTest::test.pb.affine.p2] OK
[UTest::test.pb.affine.p3] OK
[UTest::test.pb.affine.p4] OK
[UTest::test.pb.affine.p5] OK
[UTest::test.pb.affine.wfapt0] OK
[UTest::test.pb.affine.wfapt1] OK
[UTest::test.pb.edit] OK
[UTest::test.pb.indel] OK
[UTest::test.score.affine2p] OK
[UTest::test.score.affine] OK
[UTest::test.score.affine.p0] OK
[UTest::test.score.affine.p1] OK
[UTest::test.score.affine.p2] OK
[UTest::test.score.affine.p3] OK
[UTest::test.score.affine.p4] OK
[UTest::test.score.affine.p5] OK
[UTest::test.score.affine.wfapt0] OK
[UTest::test.score.affine.wfapt1] OK
[UTest::test.score.edit] OK
[UTest::test.score.indel] OK
+ grep 'Exit status:' ./tests/wfa.utest.log

------------------------------

S390x tests:
--------------------------------
> Comparing ./tests vs ./tests/wfa.utest.check
[UTest::test.affine] Error
[UTest::test.affine.p0] Error
[UTest::test.affine.p1] Error
[UTest::test.affine.p2] Error
[UTest::test.affine.p3] Error
[UTest::test.affine.p4] Error
[UTest::test.affine.p5] Error
[UTest::test.affine.wfapt0] Error
[UTest::test.affine.wfapt1] Error
[UTest::test.affine2p] Error
[UTest::test.biwfa.affine] Error
[UTest::test.biwfa.affine.p0] Error
[UTest::test.biwfa.affine.p1] Error
[UTest::test.biwfa.affine.p2] Error
[UTest::test.biwfa.affine.p3] Error
[UTest::test.biwfa.affine.p4] Error
[UTest::test.biwfa.affine.p5] Error
[UTest::test.biwfa.affine.wfapt0] Error
[UTest::test.biwfa.affine.wfapt1] Error
[UTest::test.biwfa.affine2p] Error
[UTest::test.biwfa.edit] Error
[UTest::test.biwfa.indel] Error
[UTest::test.biwfa.score.affine] Error
[UTest::test.biwfa.score.affine.p0] Error
[UTest::test.biwfa.score.affine.p1] Error
[UTest::test.biwfa.score.affine.p2] Error
[UTest::test.biwfa.score.affine.p3] Error
[UTest::test.biwfa.score.affine.p4] Error
[UTest::test.biwfa.score.affine.p5] Error
[UTest::test.biwfa.score.affine.wfapt0] Error
[UTest::test.biwfa.score.affine.wfapt1] Error
[UTest::test.biwfa.score.affine2p] Error
[UTest::test.biwfa.score.edit] Error
[UTest::test.biwfa.score.indel] Error
[UTest::test.edit] Error
[UTest::test.indel] Error
[UTest::test.pb.affine] Error
[UTest::test.pb.affine.p0] Error
[UTest::test.pb.affine.p1] Error
[UTest::test.pb.affine.p2] Error
[UTest::test.pb.affine.p3] Error
[UTest::test.pb.affine.p4] Error
[UTest::test.pb.affine.p5] Error
[UTest::test.pb.affine.wfapt0] Error
[UTest::test.pb.affine.wfapt1] Error
[UTest::test.pb.affine2p] Error
[UTest::test.pb.edit] Error
[UTest::test.pb.indel] Error
[UTest::test.score.affine] Error
[UTest::test.score.affine.p0] Error
[UTest::test.score.affine.p1] Error
[UTest::test.score.affine.p2] Error
[UTest::test.score.affine.p3] Error
[UTest::test.score.affine.p4] Error
[UTest::test.score.affine.p5] Error
[UTest::test.score.affine.wfapt0] Error
[UTest::test.score.affine.wfapt1] Error
[UTest::test.score.affine2p] Error
[UTest::test.score.edit] Error
[UTest::test.score.indel] Error

--------------------------------

**Comment by pjotrp** [comment]
Yes, you should take it up with the wfa2lib authors.

**Comment by smarco** [comment]
I remember this bug (https://github.com/smarco/WFA2-lib/issues/79). May it be a code regression. I double-checked, and the code for big-endian architectures is there. @vpa1977 Can you try running the [latest](https://github.com/smarco/WFA2-lib/releases/tag/v2.3.5) release on WFA2lib (let us open a ticket at WFA2 repo if it doesn't work standalone). Thks

**Comment by vpa1977** [comment]
Yes, thank you!!!  This update resolves the issue. The bug was raised against 2.3.3 release of WFA2 I believe.
