### ISSUE TITLE
Use build system (autotools or cmake)

### ISSUE THREAD

**Issue by agordon** [vcflib/vcflib#63]
Hello,

Are you guys open to adding support for a proper build system (either autotools or cmake) ?
I saw an old PR from 2012 (https://github.com/ekg/vcflib/pull/9 ), but it was never incorporated.

The current 'makefile' is making it hard for project to add VCFLIB as a dependency in a clean way...

If so, I could perhaps send a PR with updated build system for your consideration.

**Comment by lbeltrame** [comment]
It also makes things harder for inclusion in Linux distributions.

**Comment by ekg** [comment]
Unfortunately I let the PR for cmake support succumb to commitrot.

I support this but am not an expert in doing this. I will help it happen in
any way I can.

It may be possible to start from the cmake PR and merge in changes. I have
not checked what conflicts, but I would be surprised if it was something
fundamental.

**Comment by serverhorror** [comment]
+1 (cmake if there's any choice)

**Comment by ekg** [comment]
Someone did this before but the patch became stale.

What benefit does cmake provide? I use vcflib in a number of other projects
without issue.

**Comment by serverhorror** [comment]
Pros of build tools in general:
- I can define the installation prefix
- I can reuse existing libraries by only changing a build flag -- no patches to the source required (e.g. use another tabix version that is already installed instead of the vendored one if necessary for some reason)
- add custom C**FLags (or generally adding some flags) without patching the makefile.
- have tests included in the build process
- Debug/Release builds
- I maintain about 5-8 builds of vcflib because we want to minimize CPU time and have different optimization flags. Right now I have patches to the makefile for each build

The subjective benefit of cmake vs autotools: cmake doesn't make my eyes explode and keeps me sane whereas I simply don't like autotools (both tools are very high quality)

I want to spend as little time as possible in actually maintainig the installations -- too me that means as few patches as as somehow possible. (looky here: https://github.com/hpcugent/easybuild-easyconfigs/tree/e2de9e479830843a2644c08189edadb039f42d5e/easybuild/easyconfigs/f/fastahack, those are 2 build configs for fastahack and a required patch. Makefiles you could technically do it but it get's cumbersome past a certain point)

I have to get permission from my customers legal departement to send the vcflib there and once I have the permission I can probably create the cmake pull request here as well. But given that legal issues take a very long time I'd rather wait for the actual permission. At least then it will be possible to create an up to date pull request :)

**Comment by lbeltrame** [comment]
Il 14 giugno 2015 11:40:54 CEST, Erik Garrison notifications@github.com ha scritto:

> Someone did this before but the patch became stale.
> 
> What benefit does cmake provide? I use vcflib in a number of other
> projects
> without issue.

A proper build system would also allow vcflib to be packaged by Linux distributions. Source: I'm also a packager.

## 

Luca Beltrame
GPG key ID: 6E1A4E79

**Comment by ekg** [comment]
This is solid support. It sounds worthwhile to make the change.

I will accept any patch that implements build via cmake.

**Comment by pjotrp** [comment]
We are using cmake right now. May move to meson later.
